name: Test

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build
        run: go build -mod=readonly ./...
      - name: Verify
        run: go mod verify
      - name: Test
        run: go test -v -benchmem -run=^$ -bench=. . 2> /dev/null
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
